//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_Assignments_SetCourses", "SetCourses", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.SetCourses), "Assignments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AssDAL.Assignments))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_UpAssignments_Assignments", "Assignments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.Assignments), "UpAssignments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AssDAL.UpAssignments))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_SetCourses_Classes", "Classes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.Classes), "SetCourses", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AssDAL.SetCourses))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_Students_Classes", "Classes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.Classes), "Students", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AssDAL.Students))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_SetCourses_Courses", "Courses", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.Courses), "SetCourses", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AssDAL.SetCourses))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_SetCourses_Teachers", "Teachers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.Teachers), "SetCourses", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AssDAL.SetCourses))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ASSModel", "FK_UpAssignments_Students", "Students", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AssDAL.Students), "UpAssignments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AssDAL.UpAssignments))]

// 原始文件名:
// 生成日期: 2015-06-27 1:10:54
namespace AssDAL
{
    
    /// <summary>
    /// 架构中不存在 ASSEntities 的注释。
    /// </summary>
    public partial class ASSEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“ASSEntities”部分中的连接字符串初始化新 ASSEntities 对象。
        /// </summary>
        public ASSEntities() : 
                base("name=ASSEntities", "ASSEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 ASSEntities 对象。
        /// </summary>
        public ASSEntities(string connectionString) : 
                base(connectionString, "ASSEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 ASSEntities 对象。
        /// </summary>
        public ASSEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ASSEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Assignments 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Assignments> Assignments
        {
            get
            {
                if ((this._Assignments == null))
                {
                    this._Assignments = base.CreateQuery<Assignments>("[Assignments]");
                }
                return this._Assignments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Assignments> _Assignments;
        /// <summary>
        /// 架构中不存在 Classes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Classes> Classes
        {
            get
            {
                if ((this._Classes == null))
                {
                    this._Classes = base.CreateQuery<Classes>("[Classes]");
                }
                return this._Classes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Classes> _Classes;
        /// <summary>
        /// 架构中不存在 Courses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Courses> Courses
        {
            get
            {
                if ((this._Courses == null))
                {
                    this._Courses = base.CreateQuery<Courses>("[Courses]");
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Courses> _Courses;
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SetCourses> SetCourses
        {
            get
            {
                if ((this._SetCourses == null))
                {
                    this._SetCourses = base.CreateQuery<SetCourses>("[SetCourses]");
                }
                return this._SetCourses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SetCourses> _SetCourses;
        /// <summary>
        /// 架构中不存在 Students 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Students> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Students>("[Students]");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Students> _Students;
        /// <summary>
        /// 架构中不存在 Teachers 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Teachers> Teachers
        {
            get
            {
                if ((this._Teachers == null))
                {
                    this._Teachers = base.CreateQuery<Teachers>("[Teachers]");
                }
                return this._Teachers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Teachers> _Teachers;
        /// <summary>
        /// 架构中不存在 UpAssignments 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<UpAssignments> UpAssignments
        {
            get
            {
                if ((this._UpAssignments == null))
                {
                    this._UpAssignments = base.CreateQuery<UpAssignments>("[UpAssignments]");
                }
                return this._UpAssignments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<UpAssignments> _UpAssignments;
        /// <summary>
        /// 架构中不存在 Assignments 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToAssignments(Assignments assignments)
        {
            base.AddObject("Assignments", assignments);
        }
        /// <summary>
        /// 架构中不存在 Classes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToClasses(Classes classes)
        {
            base.AddObject("Classes", classes);
        }
        /// <summary>
        /// 架构中不存在 Courses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCourses(Courses courses)
        {
            base.AddObject("Courses", courses);
        }
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSetCourses(SetCourses setCourses)
        {
            base.AddObject("SetCourses", setCourses);
        }
        /// <summary>
        /// 架构中不存在 Students 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToStudents(Students students)
        {
            base.AddObject("Students", students);
        }
        /// <summary>
        /// 架构中不存在 Teachers 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTeachers(Teachers teachers)
        {
            base.AddObject("Teachers", teachers);
        }
        /// <summary>
        /// 架构中不存在 UpAssignments 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUpAssignments(UpAssignments upAssignments)
        {
            base.AddObject("UpAssignments", upAssignments);
        }
        /// <summary>
        /// 架构中不存在 ASSEntities.GETHOUSEWORKDONE 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<UpAssignments> GETHOUSEWORKDONE(global::System.Nullable<int> stuID, global::System.Nullable<int> classID, string semester)
        {
            global::System.Data.Objects.ObjectParameter stuIDParameter;
            if (stuID.HasValue)
            {
                stuIDParameter = new global::System.Data.Objects.ObjectParameter("StuID", stuID);
            }
            else
            {
                stuIDParameter = new global::System.Data.Objects.ObjectParameter("StuID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter classIDParameter;
            if (classID.HasValue)
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter semesterParameter;
            if ((semester != null))
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", semester);
            }
            else
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", typeof(string));
            }
            return base.ExecuteFunction<UpAssignments>("GETHOUSEWORKDONE", stuIDParameter, classIDParameter, semesterParameter);
        }
        /// <summary>
        /// 架构中不存在 ASSEntities.GETHOUSEWORKTODO 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<Assignments> GETHOUSEWORKTODO(global::System.Nullable<int> stuID, global::System.Nullable<int> classID, string semester)
        {
            global::System.Data.Objects.ObjectParameter stuIDParameter;
            if (stuID.HasValue)
            {
                stuIDParameter = new global::System.Data.Objects.ObjectParameter("StuID", stuID);
            }
            else
            {
                stuIDParameter = new global::System.Data.Objects.ObjectParameter("StuID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter classIDParameter;
            if (classID.HasValue)
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter semesterParameter;
            if ((semester != null))
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", semester);
            }
            else
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", typeof(string));
            }
            return base.ExecuteFunction<Assignments>("GETHOUSEWORKTODO", stuIDParameter, classIDParameter, semesterParameter);
        }
        /// <summary>
        /// 架构中不存在 ASSEntities.GETHOUSEWORKTODOOT 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<Assignments> GETHOUSEWORKTODOOT(global::System.Nullable<int> stuID, global::System.Nullable<int> classID, string semester)
        {
            global::System.Data.Objects.ObjectParameter stuIDParameter;
            if (stuID.HasValue)
            {
                stuIDParameter = new global::System.Data.Objects.ObjectParameter("StuID", stuID);
            }
            else
            {
                stuIDParameter = new global::System.Data.Objects.ObjectParameter("StuID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter classIDParameter;
            if (classID.HasValue)
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter semesterParameter;
            if ((semester != null))
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", semester);
            }
            else
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", typeof(string));
            }
            return base.ExecuteFunction<Assignments>("GETHOUSEWORKTODOOT", stuIDParameter, classIDParameter, semesterParameter);
        }
        /// <summary>
        /// 架构中不存在 ASSEntities.GETSTUWHOUSEWORK 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<UpAssignments> GETSTUWHOUSEWORK(global::System.Nullable<int> classID, string semester)
        {
            global::System.Data.Objects.ObjectParameter classIDParameter;
            if (classID.HasValue)
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter semesterParameter;
            if ((semester != null))
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", semester);
            }
            else
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", typeof(string));
            }
            return base.ExecuteFunction<UpAssignments>("GETSTUWHOUSEWORK", classIDParameter, semesterParameter);
        }
        /// <summary>
        /// 架构中不存在 ASSEntities.GETSTUWOHOUSEWORK 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<Students> GETSTUWOHOUSEWORK(global::System.Nullable<int> classID, string semester)
        {
            global::System.Data.Objects.ObjectParameter classIDParameter;
            if (classID.HasValue)
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new global::System.Data.Objects.ObjectParameter("ClassID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter semesterParameter;
            if ((semester != null))
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", semester);
            }
            else
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", typeof(string));
            }
            return base.ExecuteFunction<Students>("GETSTUWOHOUSEWORK", classIDParameter, semesterParameter);
        }
        /// <summary>
        /// 架构中不存在 ASSEntities.GETSTUWOHOUSEWORKOT 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<Students> GETSTUWOHOUSEWORKOT(global::System.Nullable<int> teaID, string semester)
        {
            global::System.Data.Objects.ObjectParameter teaIDParameter;
            if (teaID.HasValue)
            {
                teaIDParameter = new global::System.Data.Objects.ObjectParameter("TeaID", teaID);
            }
            else
            {
                teaIDParameter = new global::System.Data.Objects.ObjectParameter("TeaID", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter semesterParameter;
            if ((semester != null))
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", semester);
            }
            else
            {
                semesterParameter = new global::System.Data.Objects.ObjectParameter("Semester", typeof(string));
            }
            return base.ExecuteFunction<Students>("GETSTUWOHOUSEWORKOT", teaIDParameter, semesterParameter);
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.Assignments 的注释。
    /// </summary>
    /// <KeyProperties>
    /// AssID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="Assignments")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Assignments : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Assignments 对象。
        /// </summary>
        /// <param name="assID">AssID 的初始值。</param>
        /// <param name="assName">AssName 的初始值。</param>
        /// <param name="deadline">Deadline 的初始值。</param>
        /// <param name="quesFileUrl">QuesFileUrl 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Assignments CreateAssignments(int assID, string assName, global::System.DateTime deadline, string quesFileUrl)
        {
            Assignments assignments = new Assignments();
            assignments.AssID = assID;
            assignments.AssName = assName;
            assignments.Deadline = deadline;
            assignments.QuesFileUrl = quesFileUrl;
            return assignments;
        }
        /// <summary>
        /// 架构中不存在属性 AssID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int AssID
        {
            get
            {
                return this._AssID;
            }
            set
            {
                this.OnAssIDChanging(value);
                this.ReportPropertyChanging("AssID");
                this._AssID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AssID");
                this.OnAssIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _AssID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssIDChanged();
        /// <summary>
        /// 架构中不存在属性 AssName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string AssName
        {
            get
            {
                return this._AssName;
            }
            set
            {
                this.OnAssNameChanging(value);
                this.ReportPropertyChanging("AssName");
                this._AssName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AssName");
                this.OnAssNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _AssName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssNameChanged();
        /// <summary>
        /// 架构中不存在属性 Deadline 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Deadline
        {
            get
            {
                return this._Deadline;
            }
            set
            {
                this.OnDeadlineChanging(value);
                this.ReportPropertyChanging("Deadline");
                this._Deadline = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Deadline");
                this.OnDeadlineChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Deadline;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDeadlineChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDeadlineChanged();
        /// <summary>
        /// 架构中不存在属性 QuesFileUrl 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string QuesFileUrl
        {
            get
            {
                return this._QuesFileUrl;
            }
            set
            {
                this.OnQuesFileUrlChanging(value);
                this.ReportPropertyChanging("QuesFileUrl");
                this._QuesFileUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("QuesFileUrl");
                this.OnQuesFileUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _QuesFileUrl;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQuesFileUrlChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQuesFileUrlChanged();
        /// <summary>
        /// 架构中不存在属性 AssDes 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string AssDes
        {
            get
            {
                return this._AssDes;
            }
            set
            {
                this.OnAssDesChanging(value);
                this.ReportPropertyChanging("AssDes");
                this._AssDes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AssDes");
                this.OnAssDesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _AssDes;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssDesChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssDesChanged();
        /// <summary>
        /// 架构中不存在属性 QuesFileName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string QuesFileName
        {
            get
            {
                return this._QuesFileName;
            }
            set
            {
                this.OnQuesFileNameChanging(value);
                this.ReportPropertyChanging("QuesFileName");
                this._QuesFileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("QuesFileName");
                this.OnQuesFileNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _QuesFileName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQuesFileNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQuesFileNameChanged();
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_Assignments_SetCourses", "SetCourses")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SetCourses SetCourses
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SetCourses>("ASSModel.FK_Assignments_SetCourses", "SetCourses").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SetCourses>("ASSModel.FK_Assignments_SetCourses", "SetCourses").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SetCourses> SetCoursesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SetCourses>("ASSModel.FK_Assignments_SetCourses", "SetCourses");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SetCourses>("ASSModel.FK_Assignments_SetCourses", "SetCourses", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 UpAssignments 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_UpAssignments_Assignments", "UpAssignments")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<UpAssignments> UpAssignments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<UpAssignments>("ASSModel.FK_UpAssignments_Assignments", "UpAssignments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<UpAssignments>("ASSModel.FK_UpAssignments_Assignments", "UpAssignments", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.Classes 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ClassID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="Classes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Classes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Classes 对象。
        /// </summary>
        /// <param name="classID">ClassID 的初始值。</param>
        /// <param name="className">ClassName 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Classes CreateClasses(int classID, string className)
        {
            Classes classes = new Classes();
            classes.ClassID = classID;
            classes.ClassName = className;
            return classes;
        }
        /// <summary>
        /// 架构中不存在属性 ClassID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ClassID
        {
            get
            {
                return this._ClassID;
            }
            set
            {
                this.OnClassIDChanging(value);
                this.ReportPropertyChanging("ClassID");
                this._ClassID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ClassID");
                this.OnClassIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ClassID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnClassIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnClassIDChanged();
        /// <summary>
        /// 架构中不存在属性 ClassName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ClassName
        {
            get
            {
                return this._ClassName;
            }
            set
            {
                this.OnClassNameChanging(value);
                this.ReportPropertyChanging("ClassName");
                this._ClassName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ClassName");
                this.OnClassNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ClassName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnClassNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnClassNameChanged();
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_SetCourses_Classes", "SetCourses")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SetCourses> SetCourses
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SetCourses>("ASSModel.FK_SetCourses_Classes", "SetCourses");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SetCourses>("ASSModel.FK_SetCourses_Classes", "SetCourses", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 Students 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_Students_Classes", "Students")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Students> Students
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Students>("ASSModel.FK_Students_Classes", "Students");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Students>("ASSModel.FK_Students_Classes", "Students", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.Courses 的注释。
    /// </summary>
    /// <KeyProperties>
    /// CourseID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="Courses")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Courses : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Courses 对象。
        /// </summary>
        /// <param name="courseID">CourseID 的初始值。</param>
        /// <param name="courseName">CourseName 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Courses CreateCourses(int courseID, string courseName)
        {
            Courses courses = new Courses();
            courses.CourseID = courseID;
            courses.CourseName = courseName;
            return courses;
        }
        /// <summary>
        /// 架构中不存在属性 CourseID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CourseID
        {
            get
            {
                return this._CourseID;
            }
            set
            {
                this.OnCourseIDChanging(value);
                this.ReportPropertyChanging("CourseID");
                this._CourseID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CourseID");
                this.OnCourseIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CourseID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCourseIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCourseIDChanged();
        /// <summary>
        /// 架构中不存在属性 CourseName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CourseName
        {
            get
            {
                return this._CourseName;
            }
            set
            {
                this.OnCourseNameChanging(value);
                this.ReportPropertyChanging("CourseName");
                this._CourseName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CourseName");
                this.OnCourseNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CourseName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCourseNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCourseNameChanged();
        /// <summary>
        /// 架构中不存在属性 CourseDes 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CourseDes
        {
            get
            {
                return this._CourseDes;
            }
            set
            {
                this.OnCourseDesChanging(value);
                this.ReportPropertyChanging("CourseDes");
                this._CourseDes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CourseDes");
                this.OnCourseDesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CourseDes;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCourseDesChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCourseDesChanged();
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_SetCourses_Courses", "SetCourses")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SetCourses> SetCourses
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SetCourses>("ASSModel.FK_SetCourses_Courses", "SetCourses");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SetCourses>("ASSModel.FK_SetCourses_Courses", "SetCourses", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.SetCourses 的注释。
    /// </summary>
    /// <KeyProperties>
    /// SCID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="SetCourses")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SetCourses : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 SetCourses 对象。
        /// </summary>
        /// <param name="sCID">SCID 的初始值。</param>
        /// <param name="semester">Semester 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SetCourses CreateSetCourses(int sCID, string semester)
        {
            SetCourses setCourses = new SetCourses();
            setCourses.SCID = sCID;
            setCourses.Semester = semester;
            return setCourses;
        }
        /// <summary>
        /// 架构中不存在属性 SCID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SCID
        {
            get
            {
                return this._SCID;
            }
            set
            {
                this.OnSCIDChanging(value);
                this.ReportPropertyChanging("SCID");
                this._SCID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SCID");
                this.OnSCIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SCID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSCIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSCIDChanged();
        /// <summary>
        /// 架构中不存在属性 Semester 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Semester
        {
            get
            {
                return this._Semester;
            }
            set
            {
                this.OnSemesterChanging(value);
                this.ReportPropertyChanging("Semester");
                this._Semester = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Semester");
                this.OnSemesterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Semester;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSemesterChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSemesterChanged();
        /// <summary>
        /// 架构中不存在 Assignments 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_Assignments_SetCourses", "Assignments")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Assignments> Assignments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Assignments>("ASSModel.FK_Assignments_SetCourses", "Assignments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Assignments>("ASSModel.FK_Assignments_SetCourses", "Assignments", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 Classes 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_SetCourses_Classes", "Classes")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Classes Classes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Classes>("ASSModel.FK_SetCourses_Classes", "Classes").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Classes>("ASSModel.FK_SetCourses_Classes", "Classes").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Classes 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Classes> ClassesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Classes>("ASSModel.FK_SetCourses_Classes", "Classes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Classes>("ASSModel.FK_SetCourses_Classes", "Classes", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 Courses 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_SetCourses_Courses", "Courses")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Courses Courses
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Courses>("ASSModel.FK_SetCourses_Courses", "Courses").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Courses>("ASSModel.FK_SetCourses_Courses", "Courses").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Courses 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Courses> CoursesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Courses>("ASSModel.FK_SetCourses_Courses", "Courses");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Courses>("ASSModel.FK_SetCourses_Courses", "Courses", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 Teachers 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_SetCourses_Teachers", "Teachers")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Teachers Teachers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Teachers>("ASSModel.FK_SetCourses_Teachers", "Teachers").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Teachers>("ASSModel.FK_SetCourses_Teachers", "Teachers").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Teachers 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Teachers> TeachersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Teachers>("ASSModel.FK_SetCourses_Teachers", "Teachers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Teachers>("ASSModel.FK_SetCourses_Teachers", "Teachers", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.Students 的注释。
    /// </summary>
    /// <KeyProperties>
    /// StuID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="Students")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Students : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Students 对象。
        /// </summary>
        /// <param name="stuID">StuID 的初始值。</param>
        /// <param name="stuName">StuName 的初始值。</param>
        /// <param name="pswd">Pswd 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Students CreateStudents(int stuID, string stuName, string pswd)
        {
            Students students = new Students();
            students.StuID = stuID;
            students.StuName = stuName;
            students.Pswd = pswd;
            return students;
        }
        /// <summary>
        /// 架构中不存在属性 StuID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int StuID
        {
            get
            {
                return this._StuID;
            }
            set
            {
                this.OnStuIDChanging(value);
                this.ReportPropertyChanging("StuID");
                this._StuID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StuID");
                this.OnStuIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _StuID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStuIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStuIDChanged();
        /// <summary>
        /// 架构中不存在属性 StuName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string StuName
        {
            get
            {
                return this._StuName;
            }
            set
            {
                this.OnStuNameChanging(value);
                this.ReportPropertyChanging("StuName");
                this._StuName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("StuName");
                this.OnStuNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _StuName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStuNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStuNameChanged();
        /// <summary>
        /// 架构中不存在属性 Pswd 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Pswd
        {
            get
            {
                return this._Pswd;
            }
            set
            {
                this.OnPswdChanging(value);
                this.ReportPropertyChanging("Pswd");
                this._Pswd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Pswd");
                this.OnPswdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Pswd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPswdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPswdChanged();
        /// <summary>
        /// 架构中不存在 Classes 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_Students_Classes", "Classes")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Classes Classes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Classes>("ASSModel.FK_Students_Classes", "Classes").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Classes>("ASSModel.FK_Students_Classes", "Classes").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Classes 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Classes> ClassesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Classes>("ASSModel.FK_Students_Classes", "Classes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Classes>("ASSModel.FK_Students_Classes", "Classes", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 UpAssignments 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_UpAssignments_Students", "UpAssignments")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public UpAssignments UpAssignments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UpAssignments>("ASSModel.FK_UpAssignments_Students", "UpAssignments").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UpAssignments>("ASSModel.FK_UpAssignments_Students", "UpAssignments").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 UpAssignments 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<UpAssignments> UpAssignmentsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UpAssignments>("ASSModel.FK_UpAssignments_Students", "UpAssignments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<UpAssignments>("ASSModel.FK_UpAssignments_Students", "UpAssignments", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.Teachers 的注释。
    /// </summary>
    /// <KeyProperties>
    /// TeaID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="Teachers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Teachers : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Teachers 对象。
        /// </summary>
        /// <param name="teaID">TeaID 的初始值。</param>
        /// <param name="teaName">TeaName 的初始值。</param>
        /// <param name="pswd">Pswd 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Teachers CreateTeachers(int teaID, string teaName, string pswd)
        {
            Teachers teachers = new Teachers();
            teachers.TeaID = teaID;
            teachers.TeaName = teaName;
            teachers.Pswd = pswd;
            return teachers;
        }
        /// <summary>
        /// 架构中不存在属性 TeaID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TeaID
        {
            get
            {
                return this._TeaID;
            }
            set
            {
                this.OnTeaIDChanging(value);
                this.ReportPropertyChanging("TeaID");
                this._TeaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TeaID");
                this.OnTeaIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TeaID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTeaIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTeaIDChanged();
        /// <summary>
        /// 架构中不存在属性 TeaName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TeaName
        {
            get
            {
                return this._TeaName;
            }
            set
            {
                this.OnTeaNameChanging(value);
                this.ReportPropertyChanging("TeaName");
                this._TeaName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TeaName");
                this.OnTeaNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TeaName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTeaNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTeaNameChanged();
        /// <summary>
        /// 架构中不存在属性 Pswd 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Pswd
        {
            get
            {
                return this._Pswd;
            }
            set
            {
                this.OnPswdChanging(value);
                this.ReportPropertyChanging("Pswd");
                this._Pswd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Pswd");
                this.OnPswdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Pswd;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPswdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPswdChanged();
        /// <summary>
        /// 架构中不存在 SetCourses 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_SetCourses_Teachers", "SetCourses")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SetCourses> SetCourses
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SetCourses>("ASSModel.FK_SetCourses_Teachers", "SetCourses");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SetCourses>("ASSModel.FK_SetCourses_Teachers", "SetCourses", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ASSModel.UpAssignments 的注释。
    /// </summary>
    /// <KeyProperties>
    /// UpAssID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ASSModel", Name="UpAssignments")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UpAssignments : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 UpAssignments 对象。
        /// </summary>
        /// <param name="upAssID">UpAssID 的初始值。</param>
        /// <param name="fileName">FileName 的初始值。</param>
        /// <param name="fileUrl">FileUrl 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static UpAssignments CreateUpAssignments(int upAssID, string fileName, string fileUrl)
        {
            UpAssignments upAssignments = new UpAssignments();
            upAssignments.UpAssID = upAssID;
            upAssignments.FileName = fileName;
            upAssignments.FileUrl = fileUrl;
            return upAssignments;
        }
        /// <summary>
        /// 架构中不存在属性 UpAssID 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int UpAssID
        {
            get
            {
                return this._UpAssID;
            }
            set
            {
                this.OnUpAssIDChanging(value);
                this.ReportPropertyChanging("UpAssID");
                this._UpAssID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpAssID");
                this.OnUpAssIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _UpAssID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUpAssIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUpAssIDChanged();
        /// <summary>
        /// 架构中不存在属性 FileName 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this.ReportPropertyChanging("FileName");
                this._FileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileName");
                this.OnFileNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _FileName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileNameChanged();
        /// <summary>
        /// 架构中不存在属性 FileUrl 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string FileUrl
        {
            get
            {
                return this._FileUrl;
            }
            set
            {
                this.OnFileUrlChanging(value);
                this.ReportPropertyChanging("FileUrl");
                this._FileUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileUrl");
                this.OnFileUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _FileUrl;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileUrlChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFileUrlChanged();
        /// <summary>
        /// 架构中不存在属性 Result 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Result
        {
            get
            {
                return this._Result;
            }
            set
            {
                this.OnResultChanging(value);
                this.ReportPropertyChanging("Result");
                this._Result = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Result");
                this.OnResultChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Result;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnResultChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnResultChanged();
        /// <summary>
        /// 架构中不存在属性 Marks 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Marks
        {
            get
            {
                return this._Marks;
            }
            set
            {
                this.OnMarksChanging(value);
                this.ReportPropertyChanging("Marks");
                this._Marks = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Marks");
                this.OnMarksChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Marks;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMarksChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMarksChanged();
        /// <summary>
        /// 架构中不存在 Assignments 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_UpAssignments_Assignments", "Assignments")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Assignments Assignments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Assignments>("ASSModel.FK_UpAssignments_Assignments", "Assignments").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Assignments>("ASSModel.FK_UpAssignments_Assignments", "Assignments").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Assignments 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Assignments> AssignmentsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Assignments>("ASSModel.FK_UpAssignments_Assignments", "Assignments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Assignments>("ASSModel.FK_UpAssignments_Assignments", "Assignments", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 Students 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ASSModel", "FK_UpAssignments_Students", "Students")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Students Students
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Students>("ASSModel.FK_UpAssignments_Students", "Students").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Students>("ASSModel.FK_UpAssignments_Students", "Students").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Students 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Students> StudentsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Students>("ASSModel.FK_UpAssignments_Students", "Students");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Students>("ASSModel.FK_UpAssignments_Students", "Students", value);
                }
            }
        }
    }
}
